### ISSUE TITLE
Remove old rubies, add Ruby 2.4.0

### ISSUE THREAD

**Issue by dblock** [mongoid/mongo_session_store#26]
I suggest kicking those rubies < 2.3.1 out. It's all the same. 2.4.0 introduces some breaking things though.

**Comment by tombruijn** [comment]
json gem (dependency of activesupport) version 1.8.5 fixed the Ruby 2.4 native extension compilation failure.

Now I'm running into problems with devise https://github.com/plataformatec/devise/issues/4395

Otherwise not really an issue for us to support Ruby 2.4 I think. I've made a PR for it #28 and we'll see how it goes and what we can do.
